(define (problem task)
(:domain turtlebot_demo)
(:objects
    kenny - robot
    order_0 order_1 order_2 order_3 - order
)
(:init
    (robot_at kenny wp0)


    (= (order_complete order_0) 0)
    (part_of dougnut_1 order_0)
    (part_of dougnut_2 order_0)
    (part_of dougnut_3 order_0)
    (part_of dougnut_4 order_0)
    (part_of dougnut_5 order_0)
    (part_of dougnut_6 order_0)

    (= (order_complete order_1) 0)
    (part_of dougnut_7 order_1)
    (part_of dougnut_8 order_1)
    (part_of dougnut_9 order_1)
    (part_of dougnut_10 order_1)
    (part_of dougnut_11 order_1)
    (part_of dougnut_12 order_1)

    (= (order_complete order_2) 0)
    (part_of dougnut_13 order_2)
    (part_of dougnut_14 order_2)
    (part_of dougnut_15 order_2)
    (part_of dougnut_16 order_2)
    (part_of dougnut_17 order_2)
    (part_of dougnut_18 order_2)

    (= (order_complete order_3) 0)
    (part_of dougnut_19 order_3)
    (part_of dougnut_20 order_3)
    (part_of dougnut_21 order_3)
    (part_of dougnut_22 order_3)
    (part_of dougnut_23 order_3)
    (part_of dougnut_24 order_3)

    (not_inspected dougnut_1)
    (not_inspected dougnut_2)
    (not_inspected dougnut_3)
    (not_inspected dougnut_4)
    (not_inspected dougnut_5)
    (not_inspected dougnut_6)
    (not_inspected dougnut_7)
    (not_inspected dougnut_8)
    (not_inspected dougnut_9)
    (not_inspected dougnut_10)
    (not_inspected dougnut_11)
    (not_inspected dougnut_12)
    (not_inspected dougnut_13)
    (not_inspected dougnut_14)
    (not_inspected dougnut_15)
    (not_inspected dougnut_16)
    (not_inspected dougnut_17)
    (not_inspected dougnut_18)
    (not_inspected dougnut_19)
    (not_inspected dougnut_20)
    (not_inspected dougnut_21)
    (not_inspected dougnut_22)
    (not_inspected dougnut_23)
    (not_inspected dougnut_24)
)
(:goal (and

    (>= (order_complete order_0) 6)
))
)
